/* top rated */
export const FETCH_TOP_RATED_MOVIES_START = 'FETCH_TOP_RATED_MOVIES_START';
export const FETCH_TOP_RATED_MOVIES_ERROR = 'FETCH_TOP_RATED_MOVIES_ERROR';
export const FETCH_TOP_RATED_MOVIES_COMPLETE =
  'FETCH_TOP_RATED_MOVIES_COMPLETE';
/* recommended */
export const FETCH_RECOMMENDED_MOVIES_START = 'FETCH_RECOMMENDED_MOVIES_START';
export const FETCH_RECOMMENDED_MOVIES_ERROR = 'FETCH_RECOMMENDED_MOVIES_ERROR';
export const FETCH_RECOMMENDED_MOVIES_COMPLETE =
  'FETCH_RECOMMENDED_MOVIES_COMPLETE';
/* detail */
export const FETCH_MOVIE_DETAIL_START = 'FETCH_MOVIE_DETAIL_START';
export const FETCH_MOVIE_DETAIL_ERROR = 'FETCH_MOVIE_DETAIL_ERROR';
export const FETCH_MOVIE_DETAIL_COMPLETE = 'FETCH_MOVIE_DETAIL_COMPLETE';
/* actors */
export const FETCH_MOVIE_ACTORS_START = 'FETCH_MOVIE_ACTORS_START';
export const FETCH_MOVIE_ACTORS_ERROR = 'FETCH_MOVIE_ACTORS_ERROR';
export const FETCH_MOVIE_ACTORS_COMPLETE = 'FETCH_MOVIE_ACTORS_COMPLETE';
