/* recommended movies */
export const FETCH_RECOMMENDED_START = 'FETCH_RECOMMENDED_START';
export const FETCH_RECOMMENDED_ERROR = 'FETCH_RECOMMENDED_ERROR';
export const FETCH_RECOMMENDED_COMPLETE = 'FETCH_RECOMMENDED_COMPLETE';
