/* top rated movies */
export const FETCH_TOP_RATED_START = 'FETCH_TOP_RATED_START';
export const FETCH_TOP_RATED_ERROR = 'FETCH_TOP_RATED_ERROR';
export const FETCH_TOP_RATED_COMPLETE = 'FETCH_TOP_RATED_COMPLETE';
